version: '3.8'

services:
  
  #  db:
  #    image: postgres:13
  #    environment:
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: thai1201
  #      POSTGRES_DB: test_db
  #    ports:
  #      - 15432:15432
  #    volumes:
  #      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    #    depends_on:
    #      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: thaiviptn1201@gmail.com
      PGADMIN_DEFAULT_PASSWORD: thai1201
    ports:
      - 5050:80
    volumes:
      - ./pgadmin4:/var/lib/pgadmin

